// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuN7HaWbVBvp6YgS2sQk_SaGjB5dxTSGw',
    appId: '1:748297860136:web:2634173852bbcf79cbf11d',
    messagingSenderId: '748297860136',
    projectId: 'smooth-games-app',
    authDomain: 'smooth-games-app.firebaseapp.com',
    storageBucket: 'smooth-games-app.appspot.com',
    measurementId: 'G-RL6WFPELR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvQ7bAzN8ldpnCHrjANv8Lag7QHaLazQ',
    appId: '1:748297860136:android:0c75bcdae6132209cbf11d',
    messagingSenderId: '748297860136',
    projectId: 'smooth-games-app',
    storageBucket: 'smooth-games-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuziQAQiBnbhJlOeOsCHqyebPr82ewSVs',
    appId: '1:748297860136:ios:349e142991112056cbf11d',
    messagingSenderId: '748297860136',
    projectId: 'smooth-games-app',
    storageBucket: 'smooth-games-app.appspot.com',
    iosClientId: '748297860136-clpac6skh2gbtnue89da9to0besf7fj4.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.smoothGameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuziQAQiBnbhJlOeOsCHqyebPr82ewSVs',
    appId: '1:748297860136:ios:349e142991112056cbf11d',
    messagingSenderId: '748297860136',
    projectId: 'smooth-games-app',
    storageBucket: 'smooth-games-app.appspot.com',
    iosClientId: '748297860136-clpac6skh2gbtnue89da9to0besf7fj4.apps.googleusercontent.com',
    iosBundleId: 'com.smoothandesign.smoothGameApp',
  );
}
