import 'package:smooth_game_app/core/enums/smooth_card_game_type.dart';
import 'package:smooth_game_app/core/models/smooth_card_game_model.dart';

class SmoothConstants {
  static List<SmoothCardGameModel> gameCards = [
    SmoothCardGameModel(
        uid: "1",
        number: 2,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/2-pique-black.png'),
    SmoothCardGameModel(
        uid: "2",
        number: 2,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/2-trefle-black.png'),
    SmoothCardGameModel(
        uid: "3",
        number: 2,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/2-carreau-red.png'),
    SmoothCardGameModel(
        uid: "4",
        number: 2,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/2-coeur-red.png'),
    SmoothCardGameModel(
        uid: "5",
        number: 3,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/2-pique-black.png'),
    SmoothCardGameModel(
        uid: "6",
        number: 3,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/3-trefle-black.png'),
    SmoothCardGameModel(
        uid: "7",
        number: 3,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/3-carreau-red.png'),
    SmoothCardGameModel(
        uid: "8",
        number: 3,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/3-coeur-red.png'),
    SmoothCardGameModel(
        uid: "9",
        number: 4,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/4-pique-black.png'),
    SmoothCardGameModel(
        uid: "10",
        number: 4,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/4-trefle-black.png'),
    SmoothCardGameModel(
        uid: "11",
        number: 4,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/4-carreau-red.png'),
    SmoothCardGameModel(
        uid: "12",
        number: 4,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/4-coeur-red.png'),
    SmoothCardGameModel(
        uid: "13",
        number: 5,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/5-pique-black.png'),
    SmoothCardGameModel(
        uid: "14",
        number: 5,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/5-trefle-black.png'),
    SmoothCardGameModel(
        uid: "15",
        number: 5,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/5-carreau-red.png'),
    SmoothCardGameModel(
        uid: "16",
        number: 5,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/5-coeur-red.png'),
    SmoothCardGameModel(
        uid: "17",
        number: 6,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/6-pique-black.png'),
    SmoothCardGameModel(
        uid: "18",
        number: 6,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/6-trefle-black.png'),
    SmoothCardGameModel(
        uid: "19",
        number: 6,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/6-carreau-red.png'),
    SmoothCardGameModel(
        uid: "20",
        number: 6,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/6-coeur-red.png'),
    SmoothCardGameModel(
        uid: "21",
        number: 7,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/7-pique-black.png'),
    SmoothCardGameModel(
        uid: "22",
        number: 7,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/7-trefle-black.png'),
    SmoothCardGameModel(
        uid: "23",
        number: 7,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/7-carreau-red.png'),
    SmoothCardGameModel(
        uid: "24",
        number: 7,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/7-coeur-red.png'),
    SmoothCardGameModel(
        uid: "25",
        number: 8,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/8-pique-black.png'),
    SmoothCardGameModel(
        uid: "26",
        number: 8,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/8-trefle-black.png'),
    SmoothCardGameModel(
        uid: "27",
        number: 8,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/8-carreau-red.png'),
    SmoothCardGameModel(
        uid: "28",
        number: 8,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/8-coeur-red.png'),
    SmoothCardGameModel(
        uid: "29",
        number: 9,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/9-pique-black.png'),
    SmoothCardGameModel(
        uid: "30",
        number: 9,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/9-trefle-black.png'),
    SmoothCardGameModel(
        uid: "31",
        number: 9,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/9-carreau-red.png'),
    SmoothCardGameModel(
        uid: "32",
        number: 9,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/9-coeur-red.png'),
    SmoothCardGameModel(
        uid: "33",
        number: 10,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/10-pique-black.png'),
    SmoothCardGameModel(
        uid: "34",
        number: 10,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/10-trefle-black.png'),
    SmoothCardGameModel(
        uid: "35",
        number: 10,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/10-carreau-red.png'),
    SmoothCardGameModel(
        uid: "36",
        number: 10,
        name: SmoothCardGameName.lambda,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/10-coeur-red.png'),
    SmoothCardGameModel(
        uid: "37",
        number: 11,
        name: SmoothCardGameName.valet,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/valet-pique-black.png'),
    SmoothCardGameModel(
        uid: "38",
        number: 11,
        name: SmoothCardGameName.valet,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/valet-trefle-black.png'),
    SmoothCardGameModel(
        uid: "39",
        number: 11,
        name: SmoothCardGameName.valet,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/valet-carreau-red.png'),
    SmoothCardGameModel(
        uid: "40",
        number: 11,
        name: SmoothCardGameName.valet,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/valet-coeur-red.png'),
    SmoothCardGameModel(
        uid: "41",
        number: 12,
        name: SmoothCardGameName.dame,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/dame-pique-black.png'),
    SmoothCardGameModel(
        uid: "42",
        number: 12,
        name: SmoothCardGameName.dame,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/dame-trefle-black.png'),
    SmoothCardGameModel(
        uid: "43",
        number: 12,
        name: SmoothCardGameName.dame,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/dame-carreau-red.png'),
    SmoothCardGameModel(
        uid: "44",
        number: 12,
        name: SmoothCardGameName.dame,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/dame-coeur-red.png'),
    SmoothCardGameModel(
        uid: "45",
        number: 13,
        name: SmoothCardGameName.king,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/king-pique-black.png'),
    SmoothCardGameModel(
        uid: "46",
        number: 13,
        name: SmoothCardGameName.king,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/king-trefle-black.png'),
    SmoothCardGameModel(
        uid: "47",
        number: 13,
        name: SmoothCardGameName.king,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/king-carreau-red.png'),
    SmoothCardGameModel(
        uid: "48",
        number: 13,
        name: SmoothCardGameName.king,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/king-coeur-red.png'),
    SmoothCardGameModel(
        uid: "49",
        number: 14,
        name: SmoothCardGameName.as,
        symbole: SmoothCardGameSymbole.pique,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/ace-pique-black.png'),
    SmoothCardGameModel(
        uid: "50",
        number: 14,
        name: SmoothCardGameName.as,
        symbole: SmoothCardGameSymbole.trefle,
        color: SmoothCardGameColor.black,
        path: 'assets/cards/ace-trefle-black.png'),
    SmoothCardGameModel(
        uid: "51",
        number: 14,
        name: SmoothCardGameName.as,
        symbole: SmoothCardGameSymbole.carreau,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/ace-carreau-red.png'),
    SmoothCardGameModel(
        uid: "52",
        number: 14,
        name: SmoothCardGameName.as,
        symbole: SmoothCardGameSymbole.coeur,
        color: SmoothCardGameColor.red,
        path: 'assets/cards/ace-coeur-red.png'),
  ];
}
